"""Configuration file for the Sphinx documentation builder."""

# -- Path setup --------------------------------------------------------------

import os
import sys
from pathlib import Path

# Add the parent directory to the path so we can import the theme
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

# -- Project information -----------------------------------------------------

project = 'MarginBook 예제 문서'
copyright = '2025, MarginBook Theme'
author = 'MarginBook Contributors'

# -- General configuration ---------------------------------------------------

extensions = [
    'myst_parser',
    'sphinx_marginbook_theme',
]

# MyST parser configuration
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "substitution",
    "attrs_inline",
    "attrs_block",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The language for content autogenerated by Sphinx
language = 'ko'

# -- Options for HTML output -------------------------------------------------

html_theme = 'marginbook'
html_title = project

# Theme options
html_theme_options = {
    'margin_width': '300px',
    'primary_color': '#2c3e50',
    'show_nav_level': 2,
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# -- Options for LaTeX output ------------------------------------------------

# Use the theme's LaTeX configuration
from sphinx_marginbook_theme import get_latex_elements

latex_engine = 'xelatex'
latex_elements = get_latex_elements()

# LaTeX document configuration
latex_documents = [
    ('index', 'marginbook-example.tex', project, author, 'manual'),
]

# -- Options for source file encoding ----------------------------------------

source_encoding = 'utf-8'
master_doc = 'index'